"""Filter Rules Exporter for Gmail XML, Sieve Scripts, and JSON configurations.

NOTE: This project is for Proof of Concept (POC) purposes only. It is not intended for production use.
"""

from __future__ import annotations

import json
import xml.sax.saxutils as saxutils

from inboxguard.models import FilterRule


class RulesExporter:
    """Generates standard client-side filter rules from FilterRule objects."""

    @staticmethod
    def export_gmail_xml(rules: list[FilterRule]) -> str:
        """Export filter rules to standard Google Workspace / Gmail filters.xml format."""
        xml_lines = [
            "<?xml version='1.0' encoding='UTF-8'?>",
            "<feed xmlns='http://www.w3.org/2005/Atom' xmlns:apps='http://schemas.google.com/apps/2006'>",
            "  <title>Mail Filters</title>",
            "  <id>tag:mail.google.com,2008:filters</id>",
            "  <updated>2026-09-14T00:00:00Z</updated>",
            "  <author><name>inboxguard-core</name></author>",
        ]

        for idx, r in enumerate(rules, 1):
            xml_lines.append("  <entry>")
            xml_lines.append(f"    <id>tag:mail.google.com,2008:filter:{idx}</id>")
            xml_lines.append(f"    <title>{saxutils.escape(r.name)}</title>")
            xml_lines.append("    <content></content>")

            # Criteria
            if r.criteria_from:
                xml_lines.append(f"    <apps:property name='from' value='{saxutils.escape(r.criteria_from)}'/>")
            if r.criteria_subject:
                xml_lines.append(f"    <apps:property name='subject' value='{saxutils.escape(r.criteria_subject)}'/>")
            if r.criteria_has_words:
                xml_lines.append(
                    f"    <apps:property name='hasTheWord' value='{saxutils.escape(r.criteria_has_words)}'/>"
                )

            # Actions
            if r.action_apply_label:
                xml_lines.append(f"    <apps:property name='label' value='{saxutils.escape(r.action_apply_label)}'/>")
            if r.action_archive:
                xml_lines.append("    <apps:property name='shouldArchive' value='true'/>")
            if r.action_star:
                xml_lines.append("    <apps:property name='shouldStar' value='true'/>")
            if r.action_mark_read:
                xml_lines.append("    <apps:property name='shouldMarkAsRead' value='true'/>")
            if r.action_trash:
                xml_lines.append("    <apps:property name='shouldTrash' value='true'/>")

            xml_lines.append("  </entry>")

        xml_lines.append("</feed>")
        return "\n".join(xml_lines)

    @staticmethod
    def export_sieve(rules: list[FilterRule]) -> str:
        """Export filter rules to standard RFC 5228 Sieve script for Fastmail/Dovecot/ProtonMail."""
        sieve_lines = [
            "# Sieve Filter Script generated by inboxguard-core",
            'require ["fileinto", "imapflags", "regex"];',
            "",
        ]

        for r in rules:
            sieve_lines.append(f"# Rule: {r.name}")
            conditions = []
            if r.criteria_from:
                conditions.append(f'header :contains "from" "{r.criteria_from}"')
            if r.criteria_subject:
                conditions.append(f'header :contains "subject" "{r.criteria_subject}"')
            if r.criteria_has_words:
                conditions.append(f'body :contains "{r.criteria_has_words}"')

            cond_str = (
                " allof (" + ", ".join(conditions) + ")"
                if len(conditions) > 1
                else (f" {conditions[0]}" if conditions else " true")
            )

            sieve_lines.append(f"if{cond_str} {{")
            if r.action_apply_label:
                sieve_lines.append(f'    fileinto "{r.action_apply_label}";')
            if r.action_archive:
                sieve_lines.append("    # Archive action (handled by filing into folder and removing inbox flag)")
            if r.action_mark_read:
                sieve_lines.append('    setflag "\\\\Seen";')
            if r.action_star:
                sieve_lines.append('    setflag "\\\\Flagged";')
            if r.action_trash:
                sieve_lines.append("    discard;")
            sieve_lines.append("}\n")

        return "\n".join(sieve_lines)

    @staticmethod
    def export_json(rules: list[FilterRule]) -> str:
        """Export filter rules to standard JSON format."""
        return json.dumps([r.to_dict() for r in rules], indent=2)
